### ISSUE TITLE
Oddly chopped strings?

### ISSUE THREAD

**Issue by george08** [goodformandspectacle/twowaystreet#5]
Not sure, but looks like these might be getting split:
https://twowaystreet.herokuapp.com/facets/label

"no" has 6 objects, etc.

**Comment by george08** [comment]
Here's an example of a longer label that looks like it's being chopped:
https://twowaystreet.herokuapp.com/things/JCF10

Junigatsu--Mukojima yuki-furi no zu 十二月むかふ島雪ふりの図

**Comment by george08** [comment]
Another? https://twowaystreet.herokuapp.com/facets/title_translation

**Comment by literarymachine** [comment]
Could be that the elasticsearch mapping is the cause of this. If so setting the corresponding fields to [not analyzed](http://www.elastic.co/guide/en/elasticsearch/guide/master/mapping-intro.html#_index_2) will help.

**Comment by infovore** [comment]
@literarymachine - yep, these are fields that aren't set to _not analyzed_ - and because they're plaintext, they probably shouldn't be. Rather, this feels like something that'll be resolved when 'facets' doesn't just list every possible column and a link to all values. So it's a side effect of the current site code, and as @george08 has just pointed out around the table, something we might fix through a design change rather than indexing the data in a suboptimal way.

**Comment by frankieroberto** [comment]
@infovore @george08 I think this is resolved now?
